### PR TITLE
chore: Update deprecated lifecycle event

### PR DESCRIPTION
**Pull request by Yagogc**
## Description
This PR removes the warning in newer React versions for the deprecated lifecycle `componentWillReceiveProps` by replace it with `componentDidUpdate`.
 
## Related issue
This PR will fix the following issue: #21

## Note
This is shameful PR copy of #24 from @tiagoqueiros. I've been waiting a couple of months to see if the requested changes were addressed but I got bored of getting the warning for the deprecated lifecycle.

### CODE REVIEW

**Comment by okonet** [comment]
The build is failing and I don't know why. Mind checking it?

**Comment by Yagogc** [comment]
@okonet sorry for the radio silence, busy at work + holidays. Anyways:

I had ran the `lint` on my local and didn't fail unlike in Travis, so I had a look the travis log and I notice is using node v8 when my default is v10. So I moved to the same version, and rerun `npm install` which modified automatically both `package.json`, by taking away all version carets, and `package-log.json`, after this my local `lint` worked and in travis as well as you can see.

If you're ok with this and it gets merged, I wouldn't mind creating another PR with an `.nvmrc` and updated installation steps to avoid this.

**Comment by okonet** [comment]
After I did the merge I realized this won’t be released as a new version. Also one more question is if this change should be a breaking one or will older react versions work with it?

**Comment by pedroabreu** [comment]
`componentDidUpdate` is supported in React 0.14.x so it shouldn't be a breaking change.

Could this be released as a new version though ? Or is it waiting on something else to be merged ?

**Comment by okonet** [comment]
Should be released now.

**Comment by ed-sparkes** [comment]
> Should be released now.

Not sure it is ? Latest release is still 0.7.0 on NPM and on release tab here?

Thanks, Ed

**Comment by pedrocbras** [comment]
@okonet Also waiting for that release! 👍

**Comment by okonet** [comment]
Please investigate why the release didn’t work on Travis

**Comment by oliviergraziano** [comment]
@okonet i tried locally and it works for me with a clean npm install. It seems like the node_modules are cached on the Travis build, can you try and purge the cache, to see if the build works ?

**Comment by okonet** [comment]
It's released now: https://github.com/okonet/react-scroll-sync/runs/431398982

**Pull request merged**
