### PR TITLE
Update peer dependencies for react 17.x

### PR DESCRIPTION
**Pull request by joaogardenberg**
Regarding issue #47

### CODE REVIEW

**Review by okonet — APPROVED** [review]

**Comment by okonet** [comment]
Damn GitHub for iOS didn't give me the opportunity to rename the commit to make it compatible with the semantic-release so it won't be released automatically. Can you please re-create the PR with the proper commit message (should be prefixed with `fix:` afaik)

**Comment by joaogardenberg** [comment]
I can't, it already has

```
"peerDependencies": {
  "react": "0.14.x || 15.x || 16.x || 17.x",
  "react-dom": "0.14.x || 15.x || 16.x || 17.x"
}
```

**Comment by NeonSunlight** [comment]
Could you please update the subversion? For now if I install this package via npm - I still have react 16.x as peer dependency in 0.8.0 version tag.

**Comment by okonet** [comment]
I force pushed and triggered the release.

**Pull request merged**
